Namwook
smh-algorithms/algorithms pull request #30
Opened 2021-02-01 00:37 UTC by papakang22

**Course-schedule**

코스별로 무한루프가 도는 코스가있으면 false를 리턴하게 구조를 짰습니다.

**Entry-logs**

백준사이트에 문제는 입력값을 직접 입력받아야 해서 java로 풀었습니다.
map을 사용하고 내림차순정렬하여 리턴하였습니다.

**Unique-String**

테스트케이스를 잘못봐서 모든글자가 다 다른줄 알고 첫글자로만 비교하였다가 실패하여
set객체로 문자별로 중복을 제거해서 배열에 담은 후 정렬한다음 양옆과 비교하여 해결했습니다.

2021-02-01 07:59 UTC, papakang22 commented
**Balanced-brackets**

닫힌 괄호는 절대 열린괄호보다 개수가 많을 수 없다는 조건으로 해결했습니다.
for문이 다 돈 후에 open된 괄호랑 close된 괄호의 개수가 맞지 않으면 정상적인 괄호가 아니므로 false를 반환하는 로직을 마지막에 추가하였습니다.

**id-suggestions**

2020년 하반기에 재미삼아 본 카카오 코딩테스트에 나왔던 문제여서 반가웠습니다.
코테에도 1번으로 나와서 단계별로 풀이하여 쉬웠던 문제였습니다.

**reduce-array-to-the-half**

javascript로 풀 방법이 생각나지 않아 java로 풀었습니다.
개수별로 내림차순 정렬해 제일 많은 개수부터 없애고 half값과 비교하여 없애야 할 수 이상으로 없앴을 시 리턴하였습니다.

**rotting-oranges**

2차원배열에서 상하좌우 감염시키는 로직을 구현하고 배열의 깊은복사를 사용하여 
한번 감염시킬때 이전 index에서 감염시킨 오렌지의 주변을 또 감염시키지 않도록 구현했습니다. 

**search-ranking**

이 문제도 2020 하반기 카카오 코딩테스트에 나왔던 걸로 기억하며 그때도.. 효율성 테스트는 실패하였습니다. filter를 사용하여 답인 배열만 추출하여 length를 리턴하였는데 
검색 알고리즘이 제일 어려운 것 같습니다.

2021-02-01 08:12 UTC, findawayer reviewed
구현하신 것 잘 봤어요! 이번에도 심플한 코드가 인상적이네요. 의견 있는 부분 코멘트 써봤습니다.

2021-02-01 08:12 UTC, findawayer commented on src/week2.unique-string/papakang22.js
> +    }
array/set 사이 변환이나 sort 같은 코스트가 있는 작업을 수행하고 있으니 메모이제이션을 써 볼 수 있을 것 같아요. `if break` 다음에도 `else`는 생략 가능해 보이구요.

```suggestion
    const temp = arr.map(item => {
      const strSet = new Set(item.toLowerCase().split("")); //소문자로 변경 후 배열만든다음 중복을 제거
      const uniqStrArr = [...strSet]; //중복을 제거된 배열 생성
      const str = uniqStrArr.sort().join("").trim(); //정렬후 문자열로 변환 및 공백제거
      return str;
    });
    for(let i = 1; i < arr.length -1 ; i++){
      const str = temp[i];
      const nextStr = temp[i + 1];
      const prevStr = temp[i - 1];
      
      if (str != nextStr && str != prevStr){ // 양옆과 다르면 현재 순번인 문자열이 유니크값
        answer = arr[i];
        break;
      }
      if (str != nextStr && str == prevStr){ // 다음 문자열만 다르면 다음 순번인 문자열이 유니크값
        answer = arr[i+1];
        break;
      }
      if (str == nextStr && str != prevStr){ // 이전 문자열만 다르다면 이전 순번인 문자열이 유니크값
        answer = arr[i-1];
        break;
      }
    }
```

2021-02-01 08:19 UTC, findawayer commented
> **Balanced-brackets**
> 
> 닫힌 괄호는 절대 열린괄호보다 개수가 많을 수 없다는 조건으로 해결했습니다.
> for문이 다 돈 후에 open된 괄호랑 close된 괄호의 개수가 맞지 않으면 정상적인 괄호가 아니므로 false를 반환하는 로직을 마지막에 추가하였습니다.
> 
> **id-suggestions**
> 
> 2020년 하반기에 재미삼아 본 카카오 코딩테스트에 나왔던 문제여서 반가웠습니다.
> 코테에도 1번으로 나와서 단계별로 풀이하여 쉬웠던 문제였습니다.
> 
> **reduce-array-to-the-half**
> 
> javascript로 풀 방법이 생각나지 않아 java로 풀었습니다.
> 개수별로 내림차순 정렬해 제일 많은 개수부터 없애고 half값과 비교하여 없애야 할 수 이상으로 없앴을 시 리턴하였습니다.
> 
> **rotting-oranges**
> 
> 2차원배열에서 상하좌우 감염시키는 로직을 구현하고 배열의 깊은복사를 사용하여
> 한번 감염시킬때 이전 index에서 감염시킨 오렌지의 주변을 또 감염시키지 않도록 구현했습니다.
> 
> **search-ranking**
> 
> 이 문제도 2020 하반기 카카오 코딩테스트에 나왔던 걸로 기억하며 그때도.. 효율성 테스트는 실패하였습니다. filter를 사용하여 답인 배열만 추출하여 length를 리턴하였는데
> 검색 알고리즘이 제일 어려운 것 같습니다.

빠르시네요! 가능하시다면 주 단위로 나눠서 PR을 만들면 좋을 것 같아요. week3에 도전하지 않은 상태로 week2 답안을 보면서 코멘트할 수 있으니까요 😎

PR은 브랜치별로 만들어지니, 아직 머지가 끝나지 않은 PR이 있다면 papakang22-week3 같은 새 브랜치를 파셔서 거기서 새 PR을 만드시는 것도 좋아 보입니다.

2021-02-02 01:09 UTC, papakang22 commented on src/week2.unique-string/papakang22.js
> +    }
아 미리 배열을 만들어서 하는방법이 있었군요 왜 생각을 못했을까욬ㅋㅋ 감사합니다. 메모이제이션이란 단어도 처음 듣는단어네요!! 공부 더 열심히 해야겠어여

2021-02-02 01:10 UTC, papakang22 commented on src/week2.course-schedule/papakang22.js
> +}
그러네요.. else가 필요없었네용 하나 더 배워갑니다 ㅎㅎ

2021-02-08 07:53 UTC, findawayer requested changes
이번 주도 좋은 풀이 잘 보았습니다 🥇 떠오른 아이디어 코멘트 남겨봤어요!

덧붙여 week4부터는 `approve` 리뷰가 1개 이상 남겨져야 주 브랜치로 머지되도록 바뀌었어요. 새 주간에는 새로운 브랜치를 만들어서 매주 새로운 PR을 남겨주시면 될듯해요 😄

브랜치는 week 정보만 접두시켜 주시면 됩니다.

- week4.namwook
- week5.namwook

또는 

- week4.nw
- week5.nw

week 이후엔 본인이 식별만 가능하다면 마음에 드는 브랜치명을 써주세요!

2021-02-08 07:53 UTC, findawayer commented on src/week3.balacend-brackets/papakang22.js
> +}
여는/닫는 괄호 갯수를 카운트한 부분 배워가요👍
`open`과 `close`를 단일 카운트로 병합할 수 있을 것 같네요. 0을 기점으로 모든 괄호의 유효성, 그리고 `열려있는 괄호 > 닫는 괄호`도 검사할 수 있을 테니까요.

2021-02-08 07:53 UTC, findawayer commented on src/week3.id-suggestions/papakang22.js
> +    const regex = /[^a-z0-9-_.]/gi
모두 소문자로 변경됐기 때문에 case insensitive 플래그가 필요하지 않아 보여요.

2021-02-08 07:53 UTC, findawayer commented on src/week3.id-suggestions/papakang22.js
> +    new_id = new_id == '' ? 'a': new_id;
쇼트 서킷을 활용하면 약간 가독성이 높아지지 않을까 하는 생각이 들어요! 🙌

2021-02-08 07:53 UTC, findawayer commented on src/week3.reduce-array-to-the-half/papakang22.java
> +        Integer half = arr.length % 2 == 0 ? arr.length / 2 : arr.length / 2 + 1;
`Math.ceil`로 조금 더 간단하게 작성할 수 있지 않을까요?

2021-02-08 07:53 UTC, findawayer commented on src/week3.reduce-array-to-the-half/papakang22.java
> +        return answer.size();
실제로 배열 `answer`를 만들 수도 있겠지만, 각 키가 갖고 있는 원소 갯수 `Integer val`을 `Integer answer = 0`에 더해나가면 반복문이 중단됐을 때 `.size()`를 하지 않더라도 자연수 형태의 답을 도출할 수 있을 것 같아요. 공간 복잡도가 약간 절약될 것 같습니다!

2021-02-08 07:53 UTC, findawayer commented on src/week3.rotting-oranges/papakang22.js
> +    if(orgGrid.toString() == grid.toString()) return null;
`.toString()`으로 두 배열의 상태를 비교한 게 인상적이네요! 재미있는 아이디어 발견하고 갑니다.

2021-02-08 07:53 UTC, findawayer commented on src/week3.search-ranking/papakang22.js
> +}
[힌트 댓글](https://programmers.co.kr/questions/15601)을 읽어보고 어떤 식으로 접근할 수 있는지 배웠는데, 한 번 참고해 보셔요. 이 답안처럼 모든 쿼리에 대해서 `info`를 순회하며 탐색하면 시간 복잡도는 O(mn)이 되는데, 제한사항을 보면 m=50000, n=10000이 가능하네요. 이 부분을 최대한 절약하는 게 핵심이었어요.

2021-02-08 07:53 UTC, findawayer commented on src/week3.search-ranking/papakang22.js
> +           const qArr = q.split(" ").filter((qry) =>{return qry != 'and'});
쿼리 파싱은 `info.filter` 클로저 바깥에서 미리 수행하는 게 `info`의 갯수만큼 반복되는 걸 피할 수 있다고 생각해요!

2021-03-13 10:54 UTC, findawayer approved these changes

2021-03-13 10:54 UTC, merged